### ISSUE TITLE
Negative width coefficients broken

### ISSUE THREAD

**Issue by szakharchenko** [tabu-fixed/tabu#10]
The recent ``tabu`` update broke negative width coefficient support which is relied upon by e.g. Doxygen.

```
\documentclass{article}

\usepackage{longtable}
\usepackage{tabu}
\usepackage{color}

\begin{document}

% OK
\begin{longtabu} to \linewidth {llX}
    a & b & c\\
\end{longtabu}

% OK
\begin{longtabu} {|X[1]|X[1]|X[1]|}
    a & b & c\\
\end{longtabu}

% Fails
\begin{longtabu} {|X[-1]|X[-1]|X[-1]|}
    a & b & c\\
\end{longtabu}

\end{document}
```

See the log for details.

[tabu-negative-width.log](https://github.com/tabu-fixed/tabu/files/2832052/tabu-negative-width.log)

**Comment by DigNative** [comment]
I tested your MWE and can reproduce the problem on a TeX Live installation with latest packages. I can confirm that downgrading the `tabu` and `tools` package on TeX Live and MiKTeX [as described here](https://github.com/tabu-fixed/tabu/issues/1#issuecomment-464369706) solves the problem and compilation runs again without any issue.

This issue is thus related to #1.

**Comment by szakharchenko** [comment]
Thanks for the workaround @DigNative !

**Comment by FrankMittelbach** [comment]
fixed by current change (but fitx not yet final). -- added a test file, to ensure it stays fixed with next update so close it here.

**Comment by FrankMittelbach** [comment]
@szakharchenko, @DigNative   downgrading tools is really just an emergency measure as that mean that you reintroduce bugs that got fixed in core. Better, try the updated patch from here (even if that isn't yet final)
